language: python
python:
  - "3.7"

sudo: required
services:
  - docker

before_install:
  - docker build -t joaoguilherme1/recipe-app .

script:
  - docker-compose run app -e CI=true sh -c "python manage.py test && flake8"

